#---------------------------------
#   Stage 1: Build
#---------------------------------

FROM golang:latest AS baseImage

WORKDIR /app
COPY . .
RUN make build

#---------------------------------
#   Stage 2: Run
#---------------------------------
FROM alpine:latest

COPY --from=baseImage /app/out/go-app /app/go-app

EXPOSE 8080
CMD ["/app/go-app"]